resources:
  - ../../base

configMapGenerator:
  - name: user-config
    envs:
      - params.env

vars:
  - name: USERNAME
    objref:
      kind: ConfigMap
      name: user-config
      apiVersion: v1
    fieldref:
      fieldpath: data.USERNAME
  - name: NAMESPACE_NAME
    objref:
      kind: ConfigMap
      name: user-config
      apiVersion: v1
    fieldref:
      fieldpath: data.NAMESPACE_NAME