apiVersion: v1
kind: Secret
metadata:
  name: $(STORAGE_SECRET)
  namespace: $(NAMESPACE)
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type-ref: s3
    openshift.io/display-name: $(STORAGE_SECRET)
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
  AWS_S3_ENDPOINT: bWluaW8uZXhhbXBsZS5jb206OTAwMA==
  AWS_S3_BUCKET: ZGVmYXVsdC1idWNrZXQ=
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
